# Generated by Django 3.2.9 on 2022-01-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220101_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
